### ISSUE TITLE
Catastrophic KitKat Crash: Compilation Conundrum?

### ISSUE THREAD

**Issue by sanchezdanj** [SRI-CSL/langlearn#39]
User noted that "LingoBoost Has Stopped" when using a phone with KitKat.
@tim-mccarthy noted he could replicate the error using an AVD with KitKat: 
```
E/AndroidRuntime: FATAL EXCEPTION: main
                 Process: com.sri.lingoboost.debug, PID: 2534
                 java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.sri.lingoboost.debug/edu.northwestern.langlearn.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "edu.northwestern.langlearn.MainActivity" on path: DexPathList[[zip file "/data/app/com.sri.lingoboost.debug-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.sri.lingoboost.debug-2, /vendor/lib, /system/lib]]
                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2121)
                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
                     at android.app.ActivityThread.access$800(ActivityThread.java:135)
                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                     at android.os.Handler.dispatchMessage(Handler.java:102)
                     at android.os.Looper.loop(Looper.java:136)
                     at android.app.ActivityThread.main(ActivityThread.java:5017)
                     at java.lang.reflect.Method.invokeNative(Native Method)
                     at java.lang.reflect.Method.invoke(Method.java:515)
                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                     at dalvik.system.NativeStart.main(Native Method)
                  Caused by: java.lang.ClassNotFoundException: Didn't find class "edu.northwestern.langlearn.MainActivity" on path: DexPathList[[zip file "/data/app/com.sri.lingoboost.debug-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.sri.lingoboost.debug-2, /vendor/lib, /system/lib]]
                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                     at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                     at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                     at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2112)
                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
                     at android.app.ActivityThread.access$800(ActivityThread.java:135)
                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                     at android.os.Handler.dispatchMessage(Handler.java:102)
                     at android.os.Looper.loop(Looper.java:136)
                     at android.app.ActivityThread.main(ActivityThread.java:5017)
                     at java.lang.reflect.Method.invokeNative(Native Method)
                     at java.lang.reflect.Method.invoke(Method.java:515)
                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                     at dalvik.system.NativeStart.main(Native Method)
```

**Comment by sanchezdanj** [comment]
per @AddictArts, this app will not work with KitKat or below. Marking as closed. We do not want to expend the development effort to get this working w/ versions of Android below 5.0.
